[workspace]
members = [
    "components/dtd",
    "components/xts",
    "components/parser",
    "components/dom",
    "components/xpath",
    "components/chars",
]

[profile.release]
lto = true
codegen-units = 1