[workspace]
members = [
    "components/xts",
    "components/parser",
    "components/dom",
    "components/xpath",
    "components/chars",
    "components/serde",
    "components/writer",
    "components/xmlrpc",
    "components/textsimd",
]

[profile.release]
lto = true
codegen-units = 1